apiVersion: v1
kind: Pod
metadata:
    name: pod1
spec:
  containers:
  - name: pod1
    image: busybox
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      runAsNonRoot: false
      capabilities:
        add: ["NET_RAW"]